FROM nginx
EXPOSE 80/tcp
COPY qi/ /usr/share/nginx/html/

















# FROM almalinux:9
# RUN dnf install nginx -y
# CMD [ "nginx", "-g", "daemon off;" ]
# EXPOSE 80/tcp
# COPY index.html /usr/share/nginx/html/